services:
  db:
    image: postgres:15-alpine
    container_name: oui-maitre-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oui_maitre
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ..
      dockerfile: apps/server/Dockerfile
    container_name: oui-maitre-server
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Uncomment when build scripts and deps are in place:
    # command: ["node", "apps/server/dist/main.js"]

volumes:
  db_data:
